# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0003_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='reacted_user_id',
            new_name='reacted_user',
        ),
    ]
