# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0006_auto_20180713_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodels.Post'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reacted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodels.User'),
        ),
    ]
