# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-13 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0009_auto_20180713_1943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set([('post', 'reacted_user')]),
        ),
    ]
